name: Run production

on:
  repository_dispatch:
    types:
      - ppap-prd

env:
  LANGUAGE_CODE: ${{ github.event.client_payload.language_code }}
  SCRIPT_NAME: ${{ github.event.client_payload.script_name }}

jobs:
  run:
    name: Running
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crawler
        uses: actions/checkout@v4
        with:
          repository: InfluenceNews/nodejs-innews-crawler
          token: ${{ secrets.GH_PAT }}

      - name: Checkout Secrets
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          repository: InfluenceNews/secrets-file
          path: secrets-file
          ref: main

      - name: Env setup
        run: mv secrets-file/nodejs-innews-crawler/.env.prd .env

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          token: ${{ secrets.GH_PAT }}
          cache: "npm"
      - run: npm install

      - name: Run!!!
        run: npm run ${{ env.SCRIPT_NAME }}
