name: Run production

on:
  repository_dispatch:
    types:
      - ppap-prd

jobs:
  run:
    name: Running
    timeout-minutes: 5
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        include:
          - cmd: step1
          - cmd: step2
          - cmd: step3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: InfluenceNews/nodejs-innews-crawler
          token: ${{ secrets.GH_PAT }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          repository: InfluenceNews/secrets-file
          path: secrets-file
          ref: main

      - name: Env setup
        run: mv secrets-file/nodejs-innews-crawler/.env.prd .env

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          token: ${{ secrets.GH_PAT }}
          cache: "npm"
      - run: npm install
      - run: rm -rf node_modules/@distube && mv .github/libs/@distube node_modules/

      - name: Run!!!
        run: npm run ${{ matrix.cmd }}

      # - name: Run Step 1 !!!
      #   run: npm run step1

      # - name: Run Step 2 !!!
      #   run: npm run step2

      # - name: Run Step 3 !!!
      #   run: npm run step3
